### ISSUE TITLE
it doesn't work either

### ISSUE THREAD

**Issue by tldr-cell** [FayasNoushad/Channel-Auto-Post-Bot#2]
Why you're closed the issue before i've confirmation it's working properly nor not yet https://github.com/FayasNoushad/Channel-Auto-Post-Bot/issues/1
It doesn't work and crashing at the beginning with new deploy
https://del.dog/ykihobypul.txt

**Comment by FayasNoushad** [comment]
That Is problem of your heroku account. Restart dyno and try.
