### ISSUE TITLE
please make filter & replace for exceptions

### ISSUE THREAD

**Issue by claimclone** [FayasNoushad/Channel-Auto-Post-Bot#3]
hi fayas ,
please make filter & repcale for exceptions for multiple words.
waiting for your response
finest regards

**Comment by FayasNoushad** [comment]
Please explain

**Comment by claimclone** [comment]
for exam if find value-a in post descriptions can replace with custom one & can set multi env value for multiple values replacement.

**Comment by FayasNoushad** [comment]
I think it is not better. Fork and add it yourself.

If you like me please follow me.

**Comment by claimclone** [comment]
for expert mode if you can set if ( must have word/must not have ) mode for can be repost in destination channel , it's so much useful.

it means in must have mode , must in post description find value1 & if can't find bypass that post & vice versa for must not have mode.
